// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.appDbContext;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330105659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.asignaciones.Asignaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InvestigadorId")
                        .HasColumnType("int")
                        .HasColumnName("investigadorId");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("proyectoId");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("InvestigadorId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("asiganciones", (string)null);
                });

            modelBuilder.Entity("backend.eco.Ecosistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AreaLatitud")
                        .HasColumnType("float")
                        .HasColumnName("areaLatitud");

                    b.Property<float>("AreaLongitud")
                        .HasColumnType("float")
                        .HasColumnName("areaLongitud");

                    b.Property<ulong>("Conservacion")
                        .HasColumnType("bit")
                        .HasColumnName("conservacion");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcionEcosistema");

                    b.HasKey("Id");

                    b.ToTable("ecosistemas", (string)null);
                });

            modelBuilder.Entity("backend.investigador.Investigador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("email");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int")
                        .HasColumnName("experiencia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombreInvestigador");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("investigadores", (string)null);
                });

            modelBuilder.Entity("backend.proyecto.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaFinal")
                        .HasColumnType("date")
                        .HasColumnName("fechaFinal");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fechaInicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombreProyecto");

                    b.Property<float>("Presupuesto")
                        .HasColumnType("float")
                        .HasColumnName("presupuesto");

                    b.HasKey("Id");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("backend.asignaciones.Asignaciones", b =>
                {
                    b.HasOne("backend.investigador.Investigador", "Investigador")
                        .WithMany()
                        .HasForeignKey("InvestigadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.proyecto.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigador");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("backend.investigador.Investigador", b =>
                {
                    b.HasOne("backend.proyecto.Proyecto", null)
                        .WithMany("Investigadores")
                        .HasForeignKey("ProyectoId");
                });

            modelBuilder.Entity("backend.proyecto.Proyecto", b =>
                {
                    b.Navigation("Investigadores");
                });
#pragma warning restore 612, 618
        }
    }
}
